# Generated by Django 4.0.6 on 2022-08-02 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0005_address_alter_book_author_author_address'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address Entries'},
        ),
    ]
