# Generated by Django 4.0.6 on 2022-08-11 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0007_country_book_published_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Countries'},
        ),
    ]
